# Generated by Django 3.2.9 on 2021-12-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0002_alter_events_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_date',
            field=models.DateField(),
        ),
    ]
